1. Создать и вывести dataframe на основе заданного словаря

In [17]:
import numpy as np

In [18]:
exam_data = {'name': ['anastasia', 'dima', 'katherine', 'james', 'emily', 'michael',
'matthew', 'laura', 'kevin', 'jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [19]:
import pandas as pd

In [20]:
df1 = pd.DataFrame(exam_data, index=labels)
df1

        name  score  attempts qualify
a  anastasia   12.5         1     yes
b       dima    9.0         3      no
c  katherine   16.5         2     yes
d      james    NaN         3      no
e      emily    9.0         2      no
f    michael   20.0         3     yes
g    matthew   14.5         1     yes
h      laura    NaN         1      no
i      kevin    8.0         2      no
j      jonas   19.0         1     yes

2.1 Создать DataFrame "pokemon"

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
pokedex_with_megas = pd.read_csv("/content/drive/MyDrive/pokemon.csv")

In [23]:
pokedex = (pokedex_with_megas.drop_duplicates(subset=['#'], keep='first'))[0:151]
pokedex = pokedex.reset_index(drop=True)
pokedex

       #        Name   Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0      1   Bulbasaur    Grass  Poison  ...       65     45           1      False
1      2     Ivysaur    Grass  Poison  ...       80     60           1      False
2      3    Venusaur    Grass  Poison  ...      100     80           1      False
3      4  Charmander     Fire     NaN  ...       50     65           1      False
4      5  Charmeleon     Fire     NaN  ...       65     80           1      False
..   ...         ...      ...     ...  ...      ...    ...         ...        ...
146  147     Dratini   Dragon     NaN  ...       50     50           1      False
147  148   Dragonair   Dragon     NaN  ...       70     70           1      False
148  149   Dragonite   Dragon  Flying  ...      100     80           1      False
149  150      Mewtwo  Psychic     NaN  ...       90    130           1       True
150  151         Mew  Psychic     NaN  ...      100    100           1      False

[151 rows x 13 columns]

2.2 Вывести первые 10 строк

In [24]:
pokedex[0:10]

    #        Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0   1   Bulbasaur  Grass  Poison  ...       65     45           1      False
1   2     Ivysaur  Grass  Poison  ...       80     60           1      False
2   3    Venusaur  Grass  Poison  ...      100     80           1      False
3   4  Charmander   Fire     NaN  ...       50     65           1      False
4   5  Charmeleon   Fire     NaN  ...       65     80           1      False
5   6   Charizard   Fire  Flying  ...       85    100           1      False
6   7    Squirtle  Water     NaN  ...       64     43           1      False
7   8   Wartortle  Water     NaN  ...       80     58           1      False
8   9   Blastoise  Water     NaN  ...      105     78           1      False
9  10    Caterpie    Bug     NaN  ...       20     45           1      False

[10 rows x 13 columns]

2.3 Вывести индексы и метки столбцов

In [30]:
for a in pokedex.index:
  print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150

In [31]:
pokedex['#']

0        1
1        2
2        3
3        4
4        5
      ...
146    147
147    148
148    149
149    150
150    151
Name: #, Length: 151, dtype: int64

In [32]:
pokedex.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

2.4 Вывести значения строк: со 2-рой по 7

In [33]:
pokedex[1:7]

   #        Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
1  2     Ivysaur  Grass  Poison  ...       80     60           1      False
2  3    Venusaur  Grass  Poison  ...      100     80           1      False
3  4  Charmander   Fire     NaN  ...       50     65           1      False
4  5  Charmeleon   Fire     NaN  ...       65     80           1      False
5  6   Charizard   Fire  Flying  ...       85    100           1      False
6  7    Squirtle  Water     NaN  ...       64     43           1      False

[6 rows x 13 columns]

2.5 Вывести значения столбцов: с ‘hp’ по ‘speed’

In [49]:
pokedex.loc(1)["HP":"Speed"]

      HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0     45      49       49       65       65     45
1     60      62       63       80       80     60
2     80      82       83      100      100     80
3     39      52       43       60       50     65
4     58      64       58       80       65     80
..   ...     ...      ...      ...      ...    ...
146   41      64       45       50       50     50
147   61      84       65       70       70     70
148   91     134       95      100      100     80
149  106     110       90      154       90    130
150  100     100      100      100      100    100

[151 rows x 6 columns]

2.6 Вывести значения столбца ‘name’, отсортированный по убыванию

In [50]:
pokename = pokedex["Name"]
pokename.sort_values(ascending=False)

40          Zubat
144        Zapdos
39     Wigglytuff
109       Weezing
69     Weepinbell
          ...
58       Arcanine
23          Arbok
64       Alakazam
141    Aerodactyl
62           Abra
Name: Name, Length: 151, dtype: object

2.7 Выбрать и вывести строки, в которых значения столбца ‘hp’>40

In [51]:
pokedex[pokedex["HP"] > 40]

       #        Name   Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0      1   Bulbasaur    Grass  Poison  ...       65     45           1      False
1      2     Ivysaur    Grass  Poison  ...       80     60           1      False
2      3    Venusaur    Grass  Poison  ...      100     80           1      False
4      5  Charmeleon     Fire     NaN  ...       65     80           1      False
5      6   Charizard     Fire  Flying  ...       85    100           1      False
..   ...         ...      ...     ...  ...      ...    ...         ...        ...
146  147     Dratini   Dragon     NaN  ...       50     50           1      False
147  148   Dragonair   Dragon     NaN  ...       70     70           1      False
148  149   Dragonite   Dragon  Flying  ...      100     80           1      False
149  150      Mewtwo  Psychic     NaN  ...       90    130           1       True
150  151         Mew  Psychic     NaN  ...      100    100           1      False

[118 rows x 13 columns]

2.8 Используя индексатор loc выбрать и вывести значения столбца
‘name’, 'Type' и ‘Total’, в соответсвующих строках которых ‘Legendary’ =
‘True’

In [53]:
pokedex.loc[(pokedex["Legendary"] == True), ["Name", "Type 1", "Type 2", "Total"]]

         Name    Type 1  Type 2  Total
143  Articuno       Ice  Flying    580
144    Zapdos  Electric  Flying    580
145   Moltres      Fire  Flying    580
149    Mewtwo   Psychic     NaN    680