In [ ]:
import pandas as pd

In [ ]:
data = pd.DataFrame({"Dish": ["Chicken", "Fresh Cod", "Mushroom Pie", "Vegetable Burger", "Chicken", "Fresh Cod", "Mushroom Pie", "Vegetable Burger"], 
                     "With Chips":[True, True, True, True, False, False, False, False],
                     "Price ($)": [4.20, 3.00, 2.60, 2.00, 6.10, 4.90, 4.60, 3.90] 
                     })
data

               Dish  With Chips  Price ($)
0           Chicken        True        4.2
1         Fresh Cod        True        3.0
2      Mushroom Pie        True        2.6
3  Vegetable Burger        True        2.0
4           Chicken       False        6.1
5         Fresh Cod       False        4.9
6      Mushroom Pie       False        4.6
7  Vegetable Burger       False        3.9

In [ ]:
data.pivot(index="With Chips", columns="Dish", values="Price ($)")

Dish        Chicken  Fresh Cod  Mushroom Pie  Vegetable Burger
With Chips
False           6.1        4.9           4.6               3.9
True            4.2        3.0           2.6               2.0

In [ ]:
import numpy as np

In [ ]:
arr = np.random.rand(8, 6) * 100
data2 = pd.DataFrame(arr)
data2

           0          1          2          3          4          5
0  97.502455  84.751863  54.108398  21.448642  60.582050  63.519366
1  87.881124  14.894670  39.668459  65.062703  28.025977  33.556925
2  98.583391  43.358996  58.208604   8.272631  22.071487  74.092515
3  73.553073  94.862221  11.711024  34.081283  18.331989  43.696297
4  71.887270   1.496187  84.268098   8.128920  62.928916  47.302302
5   5.968490  56.586429  94.569273  86.139177  80.504425  83.550340
6  54.552209  80.597054  75.197392  97.402669  28.970051   9.487101
7   2.047813  92.204762  77.709565  92.060411  36.954812  40.897213

In [ ]:
data2.clip(30, 80)

           0          1          2          3          4          5
0  80.000000  80.000000  54.108398  30.000000  60.582050  63.519366
1  80.000000  30.000000  39.668459  65.062703  30.000000  33.556925
2  80.000000  43.358996  58.208604  30.000000  30.000000  74.092515
3  73.553073  80.000000  30.000000  34.081283  30.000000  43.696297
4  71.887270  30.000000  80.000000  30.000000  62.928916  47.302302
5  30.000000  56.586429  80.000000  80.000000  80.000000  80.000000
6  54.552209  80.000000  75.197392  80.000000  30.000000  30.000000
7  30.000000  80.000000  77.709565  80.000000  36.954812  40.897213